/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface IHelloWorldInterface extends utils.Interface {
  functions: {
    "getMessage()": FunctionFragment;
    "setMessage(string)": FunctionFragment;
    "terminate()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "getMessage" | "setMessage" | "terminate"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getMessage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setMessage",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "terminate", values?: undefined): string;

  decodeFunctionResult(functionFragment: "getMessage", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setMessage", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "terminate", data: BytesLike): Result;

  events: {
    "NewMessage(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "NewMessage"): EventFragment;
}

export interface NewMessageEventObject {
  clientAddress: string;
  blockNumber: BigNumber;
}
export type NewMessageEvent = TypedEvent<
  [string, BigNumber],
  NewMessageEventObject
>;

export type NewMessageEventFilter = TypedEventFilter<NewMessageEvent>;

export interface IHelloWorld extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IHelloWorldInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getMessage(overrides?: CallOverrides): Promise<[string]>;

    setMessage(
      newMessage: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    terminate(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  getMessage(overrides?: CallOverrides): Promise<string>;

  setMessage(
    newMessage: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  terminate(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getMessage(overrides?: CallOverrides): Promise<string>;

    setMessage(
      newMessage: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    terminate(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "NewMessage(address,uint256)"(
      clientAddress?: PromiseOrValue<string> | null,
      blockNumber?: PromiseOrValue<BigNumberish> | null
    ): NewMessageEventFilter;
    NewMessage(
      clientAddress?: PromiseOrValue<string> | null,
      blockNumber?: PromiseOrValue<BigNumberish> | null
    ): NewMessageEventFilter;
  };

  estimateGas: {
    getMessage(overrides?: CallOverrides): Promise<BigNumber>;

    setMessage(
      newMessage: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    terminate(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getMessage(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setMessage(
      newMessage: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    terminate(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
